### ISSUE TITLE
获取昵称BUG

### ISSUE THREAD

**Issue by wikylyu** [ArtisanCloud/go-socialite#29]
_providers/user.go_ 里面，获取昵称的代码有个错误

当前代码是

<pre>
func (user *User) GetNickname() string {
	if user.Attributes["nickname"] != nil {
		return user.Attributes["<b>id</b>"].(string)
	} else {
		return user.GetName()
	}
}
</pre>

显然应该是
<pre>
func (user *User) GetNickname() string {
	if user.Attributes["nickname"] != nil {
		return user.Attributes["<b>nickname</b>"].(string)
	} else {
		return user.GetName()
	}
}
</pre>

**Comment by wikylyu** [comment]
没人修复一下这个BUG吗 @Matrix-X

**Comment by Matrix-X** [comment]
谢谢你的提问，请查看最新的version
PowerWechat
[v2.0.40](https://github.com/ArtisanCloud/PowerWeChat/releases/tag/v2.0.40)
PowerSocialite
[v2.0.20](https://github.com/ArtisanCloud/PowerSocialite/releases/tag/v2.0.20)

**Comment by Matrix-X** [comment]
如果有急迫的问题，可以加入我们的企业微信群，直接提问
